/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.monitor.application;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Status of each plugin. */
@org.apache.avro.specific.AvroGenerated
public class ApplicationPluginStatus extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7732163524384192125L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ApplicationPluginStatus\",\"namespace\":\"org.radarcns.monitor.application\",\"doc\":\"Status of each plugin.\",\"fields\":[{\"name\":\"time\",\"type\":\"double\",\"doc\":\"Device timestamp in UTC (s).\"},{\"name\":\"plugin\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Name of the plugin.\"},{\"name\":\"pluginStatus\",\"type\":{\"type\":\"enum\",\"name\":\"PluginStatus\",\"doc\":\"Status of each plugin.\",\"symbols\":[\"UNAVAILABLE\",\"CONNECTING\",\"DISCONNECTING\",\"DISCONNECTED\",\"CONNECTED\",\"READY\",\"UNKNOWN\"]},\"doc\":\"The status of the plugin.\",\"default\":\"UNKNOWN\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ApplicationPluginStatus> ENCODER =
      new BinaryMessageEncoder<ApplicationPluginStatus>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ApplicationPluginStatus> DECODER =
      new BinaryMessageDecoder<ApplicationPluginStatus>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ApplicationPluginStatus> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ApplicationPluginStatus> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ApplicationPluginStatus>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ApplicationPluginStatus to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ApplicationPluginStatus from a ByteBuffer. */
  public static ApplicationPluginStatus fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Device timestamp in UTC (s). */
  @Deprecated public double time;
  /** Name of the plugin. */
  @Deprecated public java.lang.String plugin;
  /** The status of the plugin. */
  @Deprecated public org.radarcns.monitor.application.PluginStatus pluginStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ApplicationPluginStatus() {}

  /**
   * All-args constructor.
   * @param time Device timestamp in UTC (s).
   * @param plugin Name of the plugin.
   * @param pluginStatus The status of the plugin.
   */
  public ApplicationPluginStatus(java.lang.Double time, java.lang.String plugin, org.radarcns.monitor.application.PluginStatus pluginStatus) {
    this.time = time;
    this.plugin = plugin;
    this.pluginStatus = pluginStatus;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return plugin;
    case 2: return pluginStatus;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.Double)value$; break;
    case 1: plugin = (java.lang.String)value$; break;
    case 2: pluginStatus = (org.radarcns.monitor.application.PluginStatus)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return Device timestamp in UTC (s).
   */
  public java.lang.Double getTime() {
    return time;
  }

  /**
   * Sets the value of the 'time' field.
   * Device timestamp in UTC (s).
   * @param value the value to set.
   */
  public void setTime(java.lang.Double value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'plugin' field.
   * @return Name of the plugin.
   */
  public java.lang.String getPlugin() {
    return plugin;
  }

  /**
   * Sets the value of the 'plugin' field.
   * Name of the plugin.
   * @param value the value to set.
   */
  public void setPlugin(java.lang.String value) {
    this.plugin = value;
  }

  /**
   * Gets the value of the 'pluginStatus' field.
   * @return The status of the plugin.
   */
  public org.radarcns.monitor.application.PluginStatus getPluginStatus() {
    return pluginStatus;
  }

  /**
   * Sets the value of the 'pluginStatus' field.
   * The status of the plugin.
   * @param value the value to set.
   */
  public void setPluginStatus(org.radarcns.monitor.application.PluginStatus value) {
    this.pluginStatus = value;
  }

  /**
   * Creates a new ApplicationPluginStatus RecordBuilder.
   * @return A new ApplicationPluginStatus RecordBuilder
   */
  public static org.radarcns.monitor.application.ApplicationPluginStatus.Builder newBuilder() {
    return new org.radarcns.monitor.application.ApplicationPluginStatus.Builder();
  }

  /**
   * Creates a new ApplicationPluginStatus RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ApplicationPluginStatus RecordBuilder
   */
  public static org.radarcns.monitor.application.ApplicationPluginStatus.Builder newBuilder(org.radarcns.monitor.application.ApplicationPluginStatus.Builder other) {
    return new org.radarcns.monitor.application.ApplicationPluginStatus.Builder(other);
  }

  /**
   * Creates a new ApplicationPluginStatus RecordBuilder by copying an existing ApplicationPluginStatus instance.
   * @param other The existing instance to copy.
   * @return A new ApplicationPluginStatus RecordBuilder
   */
  public static org.radarcns.monitor.application.ApplicationPluginStatus.Builder newBuilder(org.radarcns.monitor.application.ApplicationPluginStatus other) {
    return new org.radarcns.monitor.application.ApplicationPluginStatus.Builder(other);
  }

  /**
   * RecordBuilder for ApplicationPluginStatus instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ApplicationPluginStatus>
    implements org.apache.avro.data.RecordBuilder<ApplicationPluginStatus> {

    /** Device timestamp in UTC (s). */
    private double time;
    /** Name of the plugin. */
    private java.lang.String plugin;
    /** The status of the plugin. */
    private org.radarcns.monitor.application.PluginStatus pluginStatus;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.radarcns.monitor.application.ApplicationPluginStatus.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.plugin)) {
        this.plugin = data().deepCopy(fields()[1].schema(), other.plugin);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.pluginStatus)) {
        this.pluginStatus = data().deepCopy(fields()[2].schema(), other.pluginStatus);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ApplicationPluginStatus instance
     * @param other The existing instance to copy.
     */
    private Builder(org.radarcns.monitor.application.ApplicationPluginStatus other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.plugin)) {
        this.plugin = data().deepCopy(fields()[1].schema(), other.plugin);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.pluginStatus)) {
        this.pluginStatus = data().deepCopy(fields()[2].schema(), other.pluginStatus);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'time' field.
      * Device timestamp in UTC (s).
      * @return The value.
      */
    public java.lang.Double getTime() {
      return time;
    }

    /**
      * Sets the value of the 'time' field.
      * Device timestamp in UTC (s).
      * @param value The value of 'time'.
      * @return This builder.
      */
    public org.radarcns.monitor.application.ApplicationPluginStatus.Builder setTime(double value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * Device timestamp in UTC (s).
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * Device timestamp in UTC (s).
      * @return This builder.
      */
    public org.radarcns.monitor.application.ApplicationPluginStatus.Builder clearTime() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'plugin' field.
      * Name of the plugin.
      * @return The value.
      */
    public java.lang.String getPlugin() {
      return plugin;
    }

    /**
      * Sets the value of the 'plugin' field.
      * Name of the plugin.
      * @param value The value of 'plugin'.
      * @return This builder.
      */
    public org.radarcns.monitor.application.ApplicationPluginStatus.Builder setPlugin(java.lang.String value) {
      validate(fields()[1], value);
      this.plugin = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'plugin' field has been set.
      * Name of the plugin.
      * @return True if the 'plugin' field has been set, false otherwise.
      */
    public boolean hasPlugin() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'plugin' field.
      * Name of the plugin.
      * @return This builder.
      */
    public org.radarcns.monitor.application.ApplicationPluginStatus.Builder clearPlugin() {
      plugin = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'pluginStatus' field.
      * The status of the plugin.
      * @return The value.
      */
    public org.radarcns.monitor.application.PluginStatus getPluginStatus() {
      return pluginStatus;
    }

    /**
      * Sets the value of the 'pluginStatus' field.
      * The status of the plugin.
      * @param value The value of 'pluginStatus'.
      * @return This builder.
      */
    public org.radarcns.monitor.application.ApplicationPluginStatus.Builder setPluginStatus(org.radarcns.monitor.application.PluginStatus value) {
      validate(fields()[2], value);
      this.pluginStatus = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'pluginStatus' field has been set.
      * The status of the plugin.
      * @return True if the 'pluginStatus' field has been set, false otherwise.
      */
    public boolean hasPluginStatus() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'pluginStatus' field.
      * The status of the plugin.
      * @return This builder.
      */
    public org.radarcns.monitor.application.ApplicationPluginStatus.Builder clearPluginStatus() {
      pluginStatus = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ApplicationPluginStatus build() {
      try {
        ApplicationPluginStatus record = new ApplicationPluginStatus();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.Double) defaultValue(fields()[0]);
        record.plugin = fieldSetFlags()[1] ? this.plugin : (java.lang.String) defaultValue(fields()[1]);
        record.pluginStatus = fieldSetFlags()[2] ? this.pluginStatus : (org.radarcns.monitor.application.PluginStatus) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ApplicationPluginStatus>
    WRITER$ = (org.apache.avro.io.DatumWriter<ApplicationPluginStatus>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ApplicationPluginStatus>
    READER$ = (org.apache.avro.io.DatumReader<ApplicationPluginStatus>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
