/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.radarcns.monitor.application;
@SuppressWarnings("all")
/** Status of each plugin. */
@org.apache.avro.specific.AvroGenerated
public enum PluginStatus {
  UNAVAILABLE, CONNECTING, DISCONNECTING, DISCONNECTED, CONNECTED, READY, UNKNOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PluginStatus\",\"namespace\":\"org.radarcns.monitor.application\",\"doc\":\"Status of each plugin.\",\"symbols\":[\"UNAVAILABLE\",\"CONNECTING\",\"DISCONNECTING\",\"DISCONNECTED\",\"CONNECTED\",\"READY\",\"UNKNOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
